language: node_js
sudo: true
node_js:
  - 8
branches:
  only:
    - deployed
before_install:
  - openssl aes-256-cbc -K $encrypted_4841a893ca69_key -iv $encrypted_4841a893ca69_iv -in serviceAccountKey.json.enc -out functions/serviceAccountKey.json -d
install:
  - npm install
script:
  - npm run build:deploy
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  skip_cleanup: true
  on:
    branch: deployed